sudo: required
language: python
python:
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9"

services:
    - postgresql

addons:
  postgresql: "9.6"

env:
    - DB_PASSWORD=''

notifications:
  email: false

cache:
    apt: true
    pip: true

before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - export PATH=/usr/local/bin:$PATH
  - export MPLBACKEND=Agg

before_install:
  - sudo apt-get update

install:
  - pip install .
  - pip install python-coveralls
  - pip install nose
  - pip install nose-exclude

script:
  - nosetests ./cathub --with-coverage --cover-inclusive --cover-package=. --cover-erase --exclude-dir=cathub/tests/local_tests
  - coverage report --omit 'docs/*,./*/tests/*,./tests/*,data/*' --show-missing

after_success:
  - coveralls
